name: Tests

on: ['push', 'pull_request']

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0']

    name: PHP ${{ matrix.php }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip
        tools: composer:v2
        coverage: none

    - name: Install PHP dependencies
      run: composer update --prefer-dist --no-interaction --no-progress

    - name: Tests
      run: php vendor/bin/pest --colors=always
